INSERT INTO `departamento` (`idDEPARTAMENTO`, `nombre`, `pais`) VALUES
(1, 'Amazonas', 'Perú'),
(2, 'Ancash', 'Perú'),
(3, 'Apurimac', 'Perú'),
(4, 'Arequipa', 'Perú'),
(5, 'Ayacucho', 'Perú'),
(6, 'Cajamarca', 'Perú'),
(7, 'Callao', 'Perú'),
(8, 'Cusco', 'Perú'),
(9, 'Huancavelica', 'Perú'),
(10, 'Huanuco', 'Perú'),
(11, 'Ica', 'Perú'),
(12, 'Junin', 'Perú'),
(13, 'La Libertad', 'Perú'),
(14, 'Lambayeque', 'Perú'),
(15, 'Lima', 'Perú'),
(16, 'Loreto', 'Perú'),
(17, 'Madre De Dios', 'Perú'),
(18, 'Moquegua', 'Perú'),
(19, 'Pasco', 'Perú'),
(20, 'Piura', 'Perú'),
(21, 'Puno', 'Perú'),
(22, 'San Martin', 'Perú'),
(23, 'Tacna', 'Perú'),
(24, 'Tumbes', 'Perú'),
(25, 'Ucayali', 'Perú');